### PR TITLE
First Doxygen output

### PR DESCRIPTION
**Pull request by metc**
@rgrover added Doxygen support in commits 04d10f65474c22480501ced491f4a32af746346f and f72edf4d503903c101c75843a9c3f32f8a2bbd44.
This is great! IMO, it is a must have for an API :smirk:

I refactored all Doxygen stuff to a specific folder (to keep some consistency, I did the same as [mbedtls](https://github.com/ARMmbed/mbedtls/tree/development/doxygen)) . I added a Makefile to generate the doc automatically and fix some typos (especially wrong Markdown syntax).

This is the very first Doxygen output and the documentation is not well formatted yet. A lot of polishing is needed... I am not native English speaker, so I cannot correct the doc or add Doxygen pages.

What we can do is publishing automatically the Doxygen documentation (for release versions) to `gh-page` so the doc is available online instantaneously (here is an example - https://tls.mbed.org/api/). I can do this job, please let me know if you are interested...

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by metc** [comment]
What is wrong with the Mr. mbed Jenkins CI @ciarmcom ?

**Comment by rgrover** [comment]
thanks so much for submitting these changes. I've merged a conservative version of your proposal into `develop`. Doxygen related files are still under flux. We'll soon merge `develop` into `master` and publish doxygen docs. (ref @iriark01)

**Comment by metc** [comment]
Thanks @rgrover  for merging this PR. According to fa755f1ab09890383a060ec437c5450d12bffc30, you are not interested in the separated folder, Makefile or a Travis CI setup ?
Should the Doxygen intro page be merge with the README file ?
Can you also explain me what is wrong with the Automatic CI ?

**Comment by rgrover** [comment]
Chris (ref @metc), we're aiming to host documentation using docs.mbed.com. Integration with this system is currently under progress. We'll be releasing something shortly.

**Comment by metc** [comment]
Great, makes sense. Please let me know if I can help.

**Comment by rgrover** [comment]
You can help by continuing to submit improvements to the documentation.

**Comment by rgrover** [comment]
@metc : https://docs.mbed.com/docs/ble-api/en/latest/api/index.html

**Comment by metc** [comment]
Thanks @rgrover Need some polishing but this is a good start :notes: See #120 
Do you have to publish the Doxygen output manually or is the process automated ?

**Comment by rgrover** [comment]
@metc: presently, it is a manual process triggered from the 'master' branch. So it would take some time before changes make it to the user-visible documentation; but we can trigger a rebuild if there are significant improvements to docs. @iriark01

**Pull request merged**
