### PR TITLE
BLE::init() now takes in a callback paramter

### PR DESCRIPTION
**Pull request by rgrover**
There's a completion callback.
This will require corresponding change to ble-nrf51822. Demos will need to be adapted.

Please review @pan- @andresag01 @marcuschangarm @jaustin

### CODE REVIEW

**Comment by rgrover** [comment]
please note that this changes the minor number.

**Comment by rgrover** [comment]
refer to https://github.com/ARMmbed/ble/issues/90

**Comment by marcuschangarm** [comment]
I would bump the major version number for something like this. Looks good though.

**Comment by pan-** [comment]
It looks good to me but I'm worried about the default parameter in the init member function. 
Of course, it will not break the existing examples and the existing code at compile time but with this "silent" change, the existing code can be already broken at runtime if you use a target which does not initialize immediately.

**Comment by marcuschangarm** [comment]
@pan- that was actually my point with the major version change - with the version bump it wont be a silent change.

**Comment by rgrover** [comment]
@pan-  I believe we will be updating all examples to reflect the new init API; so the impact to future dual-chip targets would be minimized. We'll also inform our existing target-owners.
I'm happy with the idea of bumping the major version number.
We should allow the default parameter for init so that people using nRF don't get surprized when they upgrade to the latest of BLE_API

**Pull request merged**
