### PR TITLE
BLE::init() should also be able to take an <object, member> tuple for its callback

### PR DESCRIPTION
**Pull request by rgrover**
please review: @pan- @marcuschangarm 
this is urgent.

### CODE REVIEW

**Comment by rgrover** [comment]
this change will require updating the demos again :(
the new bleInitComplete() would look like:

```
void bleInitComplete(BLE::InitializationCompleteCallbackContext *params)
{
    BLE &ble          = params->ble;
    ble_error_t error = params->error;
    ....
``

**Comment by marcuschangarm** [comment]
That's what the major version number is for! :)

**Comment by pan-** [comment]
I have few remarks about this issue: 
  * Why the `InitializationCompleteCallback_t ` takes a pointer to an InitializationCompleteCallbackContext as a parameter instead of a reference? If the value pointed can't be null, I think it would be better if we use a reference. But if it is for the sake of consistency accross BLE API I think it is better to use a pointer.
  * For the future, do you think it would be good if we provide a dummy function pointer implementation which map correctly true function pointer concepts ?
    - it should be [callable](http://en.cppreference.com/w/cpp/concept/Callable) 
    - it should be [nullable](http://en.cppreference.com/w/cpp/concept/NullablePointer) 
    - it should be [CopyConstructible](http://en.cppreference.com/w/cpp/concept/CopyConstructible)
    - it should be [Defaultconstructible](http://en.cppreference.com/w/cpp/concept/DefaultConstructible) 
    - it should be [EqualityComparable](http://en.cppreference.com/w/cpp/concept/EqualityComparable)
   
If we have a tool like that, this little change would have just been a typedef modification to a FunctionPointer.

**Comment by rgrover** [comment]
@pan- @marcuschangarm 
this latest implementation build correctly for <object, method> use.

**Comment by rgrover** [comment]
@pan- I agree with your suggestion that we can implement the FunctionPointer concept more properly.

**Pull request merged**
