### PR TITLE
use the github url public url in module.json

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by rgrover** [comment]
@jrobeson: I got this from the author of Yotta: "I find that git URLs are more convenient if you have SSH keys set up (like I presume we all do), as you don't have to type in any credentials."

Could you explain why you'd like to switch to https URLs?

**Comment by 0xc0170** [comment]
There are similar PR for another repositories from @jrobeson changing this. I'll add my comment here - 
I am personally inclined to use ssh

**Comment by jrobeson** [comment]
the ssh url doesn't work so well for the majority of windows users afait.

**Comment by jrobeson** [comment]
and according to https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-ssh  you must have a github account, which means no cloning without an account: 

```
These URLs provide access to a Git repository via SSH, which is a secure protocol. To use these URLs, you must have an SSH keypair generated on your computer, and attached to your GitHub account.
```

**Pull request merged**
